module.exports = {
  apps: [
    {
      name: 'techdirector-api',
      script: 'dist/main.js',
      cwd: './apps/api',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      out_file: './logs/api.log',
      error_file: './logs/api.error.log',
      log_date_format: 'HH:mm:ss',
    },
    {
      name: 'techdirector-web',
      script: '../../node_modules/next/dist/bin/next',
      args: 'start -p 3001',
      cwd: './apps/web',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      out_file: './logs/web.log',
      error_file: './logs/web.error.log',
      log_date_format: 'HH:mm:ss',
    },
    {
      name: 'techdirector-tbot',
      script: 'C:\\Users\\joaor\\Documents\\release-notes-ai\\apps\\tbot\\venv\\Scripts\\python.exe',
      args: '-m uvicorn main:app --host 0.0.0.0 --port 8000',
      cwd: 'C:\\Users\\joaor\\Documents\\release-notes-ai\\apps\\tbot',
      interpreter: 'none',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      out_file: './logs/tbot.log',
      error_file: './logs/tbot.error.log',
      log_date_format: 'HH:mm:ss',
    },
    {
      // Cloudflare Quick Tunnel pro TBot + atualiza TBOT_URL no Railway sozinho.
      // Sobe o TBot local pra que o admin em produção consiga alcançá-lo.
      name: 'techdirector-tunnel',
      script: 'tools/tunnel-manager.mjs',
      cwd: 'C:\\Users\\joaor\\Documents\\release-notes-ai',
      interpreter: 'node',
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      out_file: './logs/tunnel.log',
      error_file: './logs/tunnel.error.log',
      log_date_format: 'HH:mm:ss',
    },
  ],
};
